routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcomeindex');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route to Manage Membership
Route::resource('membership', 'CreateMembershipController');

//Route to Manage Members
Route::resource('members', 'ManageMemberController');


//Route to Accomodate Selection Of Membership Plan
Route::get('register/{register}', '\App\Http\Controllers\Auth\RegisterController@proceedRegistration');

// Payment Confirmation
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');

// Route to The Payment Controller
Route::resource('payment', 'PaymentController', ['only'=>['show']]);
//Route::resource('payment', 'PaymentController', ['only'=>['show', 'redirectToGateway', 'handleGatewayCallback']]);

// Payment Form
Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay'); // Laravel 5.1.17 and above

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="row">
                    <div class="list-group">
                        @php
                            $menu = isset($menu)? $menu : "dashboard";
                        @endphp
                        {{-- Menu Listing Here --}}
                        @if(\Auth::user()->level == 1)
                            <div class="list-group-item list-group-item-heading">
                                Menu
                            </div>
                            <a href="{{route('home')}}"
                               class="list-group-item {{ $menu == 'dashboard' ? 'active': ''}} ">
                                Dashboard <i class="glyphicon glyphicon-dashboard"></i>
                            </a>
                            <a href="{{route('membership.create')}}"
                               class="list-group-item {{ $menu == 'membership.create' ? 'active': ''}}">
                                Create Membership <i class="glyphicon-user glyphicon"></i>
                            </a>
                            <a href="{{route('membership.index')}}"
                               class="list-group-item {{ $menu == 'membership.index' ? 'active': ''}}">
                                Manage Membership <i class="glyphicon-user glyphicon"></i>
                            </a>
                            <a href="{{route('members.index')}}"
                               class="list-group-item {{ $menu == 'members.index' ? 'active': ''}}">
                                Manage Members <i class="glyphicon-user glyphicon"></i>
                            </a>
                        @else
                            <div class="list-group-item list-group-item-heading">
                                Menu
                            </div>
                            <a href="{{route('home')}}"
                               class="list-group-item {{ $menu == 'dashboard' ? 'active': ''}} ">
                                Dashboard <i class="glyphicon glyphicon-dashboard"></i>
                            </a>
                        {{-- TODO Implement the Payment History Application --}}
                            <a href="{{route('home')}}"
                               class="list-group-item {{ $menu == 'paymenthistory' ? 'active': ''}} ">
                                Payment History <i class="glyphicon glyphicon-credit-card"></i>
                            </a>
                        @endif
                    </div>
                </div>
            </div>
            <div class="col-md-10 col-md-offset-0">
                @section('subcontent')
                    <div class="panel panel-default">
                        <div class="panel-heading">Dashboard</div>

                        <div class="panel-body">
                            You are logged in!
                        </div>
                    </div>
                @show
            </div>
        </div>
    </div>
@endsection

resources/views/test.blade.php
@foreach ($tasks as $task)
	{{ $task }} <br>
@endforeach

resources/views/welcomeOLD.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>
                        <a href="{{ route('register') }}">Register</a>
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Laravel
                </div>

                <div class="links">
                    <a href="https://laravel.com/docs">Documentation</a>
                    <a href="https://laracasts.com">Laracasts</a>
                    <a href="https://laravel-news.com">News</a>
                    <a href="https://forge.laravel.com">Forge</a>
                    <a href="https://github.com/laravel/laravel">GitHub</a>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/welcomeindex.blade.php
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>        
	    <!-- Meta Descriptions -->
	    <meta charset="utf-8"/>
	    <title>Uplift Academy :: Home</title>
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta content="width=device-width, initial-scale=1" name="viewport"/>
	    <meta content="Uplift Academy." name="Learn how to code from scratch at your own pace"/>
	    <meta content="Uplift" name="Uplift Nigeria"/><meta content="Coding Academy" name="Uplift Nigeria"/>
	    
	    <!-- css Files -->
	    <link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
	    <link href='http://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>
	    <link rel="stylesheet" type="text/css" href="css/uplift.css">
	    <link rel="stylesheet" type="text/css" href="css/font-awesome-4.7.0/css/font-awesome.min.css">

	    <!-- Js Script -->
	    <script type="text/javascript" href=""></script>
	</head>
	<body>
		<div class="container">
			<div class="image-carousel">
				<div class="css-carousel">

				</div>
			</div>
			<div class="content">
				<div class="heading">
					<h1>Uplift Academy</h1>
					<p>Coding classes for beginners: Learn to code responsive websites, build interactive apps, and become a job-ready Computer Expert at Uplift Academy.</p>
				</div>
				<div class="heading"><h2>Avaliable Courses!</h2></div>
					<div class="courses">
						<div class="course-list">
							<div class="list">
								<i class="fa fa-desktop fa-3x"></i>
								<h1>Computer Appreciation</h1>
								<p>Here you'll learn how to use HTML and CSS and JavaScript to make responsive webpages...</p>
								<a class="apply" href="javascript:;">Apply Now</a>
							</div>
							<div class="list">
								<i class="fa fa-desktop fa-3x"></i>
								<h1>Computer Appreciation Advanced</h1>
								<p>Here you'll learn how to use HTML and CSS and JavaScript...</p>
								<a class="apply" style="margin-top: 0px;" href="javascript:;">Apply Now</a>
							</div>
							<div class="list">
								<i class="fa fa-desktop fa-3x"></i>
								<h1>Computer Appreciation Pro</h1>
								<p>Here you'll learn how to use HTML and CSS and JavaScript to make responsive webpages...</p>
								<a class="apply" href="javascript:;">Apply Now</a>
							</div>
							<div class="list">
								<i class="fa fa-key fa-3x"></i>
								<h1>Starter Program</h1>
								<p>Here you'll learn how to use HTML and CSS and JavaScript to make responsive webpages...</p>
								<a class="apply" href="javascript:;">Apply Now</a>
							</div>
							<div class="list">
								<i class="fa fa-laptop fa-3x"></i>
								<h1>Front End Development</h1>
								<p>Here you'll learn how to use HTML and CSS and JavaScript to make responsive webpages...</p>
								<a class="apply" href="javascript:;">Apply Now</a>
							</div>
							<div class="list">
								<i class="fa fa-gear fa-3x"></i>
								<h1>Back End Development</h1>
								<p>Here you'll learn how to use HTML and CSS and JavaScript to make responsive webpages...</p>
								<a class="apply" href="javascript:;">Apply Now</a>
							</div>
							<div class="list">
								<i class="fa fa-wordpress fa-3x"></i>
								<h1>CMS :: Wordpress</h1>
								<p>Here you'll learn how to use HTML and CSS and JavaScript to make responsive webpages...</p>
								<a class="apply" href="javascript:;">Apply Now</a>
							</div>
							<div class="list">
								<i class="fa fa-dashboard fa-3x"></i>
								<h1>IoT & Programming</h1>
								<p>Here you'll learn how to use HTML and CSS and JavaScript to make responsive webpages...</p>
								<a class="apply" href="javascript:;">Apply Now</a>
							</div>
						</div>
					</div>
			</div>
		</div>
	</body>
</html>