routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcomeindex');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route to Manage Membership
Route::resource('membership', 'CreateMembershipController');

//Route to Manage Members
Route::resource('members', 'ManageMemberController');


//Route to Accomodate Selection Of Membership Plan
Route::get('register/{register}', '\App\Http\Controllers\Auth\RegisterController@proceedRegistration');

// Payment Confirmation
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');

// Route to The Payment Controller
Route::resource('payment', 'PaymentController', ['only'=>['show']]);
//Route::resource('payment', 'PaymentController', ['only'=>['show', 'redirectToGateway', 'handleGatewayCallback']]);

// Payment Form
Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay'); // Laravel 5.1.17 and above

app/Models/Membership.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Membership extends Model
{
    /**
     *  The attributes that aren't mass assignable
     *	@var array
     */
    protected $guarded =  ['id'];
}

resources/views/membership/create.blade.php
@extends('membership.sublayout')

@php($title = isset($title)? $title : 'Create New Membership')

@php($menu = isset($menu)? $menu : 'membership.create')


@section('subcontent')
   <div class="panel panel-default">
                <div class="panel-heading">Create New Membership</div>

                <div class="panel-body">
                    <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{{ route('membership.store') }}">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <fieldset class="col-md-6 col-md-offset-4 ">
                            <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                                <label class="form-control-label">Membership Related Image: </label>
                                <input type="file" class="form-control-file" name="image">
                            </div>
                            <div class="form-group{{ $errors->has('membership_title') ? ' has-error' : '' }}">
                                <label class="form-control-label">Membership Title: </label>
                                <input  required="required" class="form-control" type="text" name="membership_title" value="{{old('membership_title', '')}}" placeholder="Membership Title">
                            </div>
                            
                            <div class="form-group{{ $errors->has('membership_fee') ? ' has-error' : '' }}" >
                            <label class="form-control-label">Membership Fee (&#8358;): </label>
                                <input  required="required" class="form-control" type="number" name="membership_fee" value="{{old('membership_fee', '')}}" placeholder="Membership Fee">
                            </div>
                            <div class="form-group{{ $errors->has('membership_desc') ? ' has-error' : '' }}">
                                <label class="form-control-label">Membership Description: </label>
                                <textarea name="membership_desc"  required="required" class="form-control" placeholder="Membership Description">{{old('membership_desc', '')}}</textarea>
                            </div>
                            <div class="form-group">
                                <input  class="btn btn-success" type="submit" name="Submit" value="Add Membership">
                            </div>
                        </fieldset>
                    </form>
                </div>
    </div>
@endsection

resources/views/membership/edit.blade.php
@extends('membership.sublayout')

@php($title = isset($title)? $title : "Update  Membership")

@php($menu = isset($menu)? $menu : 'membership.index')


@section('subcontent')
   <div class="panel panel-default">
                <div class="panel-heading">Update Current Membership</div>

                <div class="panel-body">
                    @if (\Session::has('success_message'))
                        <div class="alert alert-success">{{ \Session::get('success_message') }}</div>
                    @endif

                    @if (\Session::has('error_message' ))
                        <div class="alert alert-danger">{{ \Session::get('error_message' )}}</div>
                    @endif
                    <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{{ url('membership/'.$membership->id) }}">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="_method" value="PUT">
                        <fieldset class="col-md-6 col-md-offset-4 ">

                            <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                                <img src="{{Storage::exists($membership->image)? \Storage::url($membership->image) : \Storage::url('images/defaultmembershiplogo.jpg') }}" class="img-fluid img-responsive" id="image_logo"  alt="{{ $membership->membership_title}}">
                                <label class="form-control-label">Membership Related Image: </label>
                                <input type="file" class="form-control-file" name="image">
                            </div>
                            <div class="form-group{{ $errors->has('membership_title') ? ' has-error' : '' }}">
                                <label class="form-control-label">Membership Title: </label>
                                <input  required="required" class="form-control" type="text" name="membership_title" value="{{old('membership_title', $membership->membership_title)}}" placeholder="Membership Title">
                            </div>
                            
                            <div class="form-group{{ $errors->has('membership_fee') ? ' has-error' : '' }}" >
                            <label class="form-control-label">Membership Fee (&#8358;): </label>
                                <input  required="required" class="form-control" type="number" name="membership_fee" value="{{old('membership_fee', $membership->membership_fee)}}" placeholder="Membership Fee">
                            </div>
                            <div class="form-group{{ $errors->has('membership_desc') ? ' has-error' : '' }}">
                                <label class="form-control-label">Membership Description: </label>
                                <textarea name="membership_desc"  required="required" class="form-control" placeholder="Membership Description">{{old('membership_desc', $membership->description)}}</textarea>
                            </div>
                            <div class="form-group">
                                <input  class="btn btn-success" type="submit" name="Submit" value="Update Membership">
                            </div>
                        </fieldset>
                    </form>
                </div>
    </div>
@endsection

resources/views/membership/index.blade.php
@extends('membership.sublayout')

@php($title = isset($title)? $title : 'All Membership')

@php($menu = isset($menu)? $menu : 'membership.index')


@section('subcontent')
   <div class="panel panel-default">
                <div class="panel-heading">All Membership</div>
                   
                <div class="panel-body">
                    @if (\Session::has('success_message'))
                        <div class="alert alert-success">{{ \Session::get('success_message') }}</div>
                    @endif

                    @if (\Session::has('error_message' ))
                        <div class="alert alert-danger">{{ \Session::get('error_message' )}}</div>
                    @endif

                    <div class="row">
                        @php($formatter = new \NumberFormatter('en_NG', \NumberFormatter::CURRENCY))
                        @php($count = 0)
                        @foreach ($memberships as $key => $eachMembership)
                        
                            <div class="col-md-4 ">
                                <div class="panel {{ $eachMembership->status == 1 ? 'bg-success panel-success' : 'bg-warning panel-warning' }}">
                                    <div class="panel panel-heading  text-center align-content-center">
                                        <h4><strong>{{$eachMembership->membership_title}}</strong></h4>
                                        <hr>
                                        <img src="{{Storage::exists($eachMembership->image)? \Storage::url($eachMembership->image) : \Storage::url('images/defaultmembershiplogo.jpg') }}" class="img-fluid img-responsive" id="image_logo"  alt="{{ $eachMembership->membership_title }}" />
                                    </div>
                                    <div class="panel-body">
                                        <p>{{ substr(str_pad($eachMembership->description,50 ,"  " ), 0, 50) }}</p>
                                        <h4 class="text-info">Fee: {!! $formatter->format($eachMembership->membership_fee, 0 ) !!}</h4>
                                    </div>
                                    <div class="panel-footer">
                                        <a href="#" class="btn btn-success btn-block" >Select</a>
                                        <a href="{{url('membership/'.$eachMembership->id.'/edit')}}" class="btn btn-info btn-block" >Edit</a>

                                        {{-- This is the form --}}

                                        <form class="form-horizontal" method="post" action="{{url('membership/'.$eachMembership->id)}}">

                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="hidden" name="_method" value="DELETE">         
                                            <div class="">
                                                @if ($eachMembership->status == 1)
                                                    <input type="submit" href="{{url('membership/'.$eachMembership->id.'/edit')}}" class="btn btn-block btn-danger btn-secondary" value="De-Activate" />
                                                @else
                                                    <input type="submit" href="{{url('membership/'.$eachMembership->id.'/edit')}}" class="btn btn-warning btn-block" value="Activate" />
                                                @endif
                                            </div>
                                        </form>
                                        {{-- This is the end of the form for Activate and De-Activate --}}
                                    </div>
                                </div>
                            </div>
                        @endforeach
                        <div class="col-md-4"></div>
                    </div>
                </div>
    </div>
@endsection

resources/views/membership/show.blade.php
@extends('membership.sublayout')

@php($title = isset($title)? $title : "Update  Membership")

@php($menu = isset($menu)? $menu : 'membership.index')


@section('subcontent')
   <div class="panel panel-default">
                <div class="panel-heading">View Membership</div>

                <div class="panel-body">
                    @if (\Session::has('success_message'))
                        <div class="alert alert-success">{{ \Session::get('success_message') }}</div>
                    @endif

                    @if (\Session::has('error_message' ))
                        <div class="alert alert-danger">{{ \Session::get('error_message' )}}</div>
                    @endif
                    <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{{ url('membership/'.$membership->id) }}">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="_method" value="PUT">
                        <fieldset class="col-md-6 col-md-offset-4 ">

                            <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                                <img src="{{Storage::exists($membership->image)? \Storage::url($membership->image) : \Storage::url('images/defaultmembershiplogo.jpg') }}" class="img-fluid img-responsive" id="image_logo"  alt="{{ $membership->membership_title}}">
                                <label class="form-control-label">Membership Related Image: </label>
                            </div>
                            <div class="form-group{{ $errors->has('membership_title') ? ' has-error' : '' }}">
                                <label class="form-control-label">Membership Title: </label>
                                <div  required="required" class="form-control-static" type="text" name="membership_title">{{ $membership->membership_title }}</div>
                            </div>
                            
                            <div class="form-group{{ $errors->has('membership_fee') ? ' has-error' : '' }}" >
                            <label class="form-control-label">Membership Fee (&#8358;): {{ $membership->membership_fee }}</label>
                            </div>
                            <div class="form-group{{ $errors->has('membership_desc') ? ' has-error' : '' }}">
                                <label class="form-control-label">Membership Description: </label>
                                <div name="membership_desc"  required="required" class="form-control-static" placeholder="Membership Description">{{$membership->description}}</div>
                            </div>
                            <div class="form-group">
                                <a href="{{url('membership/'.$membership->id.'/edit')}}"  class="btn btn-success" >Edit Membership</a>
                                <a href="{{url('membership/')}}"  class="btn btn-info" >View All Membership</a>
                            </div>
                        </fieldset>
                    </form>
                </div>
    </div>
@endsection

resources/views/membership/sublayout.blade.php
@extends('home')
{{-- Membership SubLayout --}}
@section('content')
    @parent
@endsection

@section('subcontent')
    @parent
@endsection